/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

SELECT *
FROM fact_sales;

SELECT *
FROM dim_customers;

SELECT *
FROM dim_products;

-- Total customers by country
SELECT country, COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by Gender
SELECT gender AS Gender, COUNT(customer_key)
FROM dim_customers
GROUP BY gender;

-- Total Products by category
SELECT category, COUNT(product_key) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average cost by category
SELECT category, AVG(cost) AS Avg_cost
FROM dim_products
GROUP BY category
ORDER BY Avg_cost DESC;

-- Total revenue generated by each category
SELECT dp.category, SUM(fs.sales_amount) AS total_revenue
FROM fact_sales fs
LEFT JOIN dim_products dp ON fs.product_key=dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Total revenue generated by each customer
SELECT f.customer_key, d.first_name, d.last_name, SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_customers d on f.customer_key=d.customer_key
GROUP BY f.customer_key, d.first_name, d.last_name
ORDER BY total_revenue DESC;

-- Distribution of sold items across countries
SELECT d.country, SUM(f.quantity) AS total_quantity
FROM fact_sales f
LEFT JOIN dim_customers d ON f.customer_key=d.customer_key
GROUP BY d.country
ORDER BY total_quantity DESC;